"""
CSV Metrics Reader and Plotter for Success and Collision Metrics

This script reads the CSV file generated by the quadcopter environment
and plots the success rate and collision rate over time.

Usage:
    python plot_metrics.py <path_to_csv_file>
    
Example:
    python plot_metrics.py logs/skrl/quadcopter_winding_corridor_direct/2025-12-31_15-30-00_ppo_torch/metrics/success_collision_metrics_20251231_153000.csv
"""

import argparse
import csv
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path


def smooth_curve(values, weight=0.6):
    """Apply exponential moving average smoothing (like TensorBoard).
    
    Args:
        values: Array of values to smooth
        weight: Smoothing weight (0-1), higher = more smoothing
    
    Returns:
        Smoothed values
    """
    smoothed = []
    last = values[0] if len(values) > 0 else 0
    
    for value in values:
        smoothed_val = last * weight + (1 - weight) * value
        smoothed.append(smoothed_val)
        last = smoothed_val
    
    return smoothed


def plot_metrics(csv_path: str, save_plot: bool = True):
    """Plot success and collision metrics from CSV file in TensorBoard style.
    
    Args:
        csv_path: Path to the CSV file
        save_plot: Whether to save the plot as an image file
    """
    # Read CSV file
    df = pd.read_csv(csv_path)
    
    print(f"Loaded {len(df)} data points from {csv_path}")
    print(f"\nSummary Statistics:")
    print(f"  Total Episodes: {df['total_episodes'].sum()}")
    print(f"  Total Successes: {df['success_count'].sum()}")
    print(f"  Total Collisions: {df['collision_count'].sum()}")
    print(f"  Final Success Rate: {df['success_rate'].iloc[-1]:.2f}%")
    print(f"  Final Collision Rate: {df['collision_rate'].iloc[-1]:.2f}%")
    
    # TensorBoard style settings
    plt.style.use('seaborn-v0_8-darkgrid')
    
    # TensorBoard color scheme
    TB_ORANGE = '#FF6F00'  # TensorBoard's signature orange
    TB_BLUE = '#1E88E5'    # TensorBoard's blue
    TB_GREEN = '#00897B'   # TensorBoard's teal/green
    TB_RED = '#E53935'     # TensorBoard's red
    
    # Create figure with TensorBoard-like layout
    fig = plt.figure(figsize=(14, 10))
    fig.patch.set_facecolor('white')
    
    # Grid layout (2 rows, 2 columns for better organization)
    gs = fig.add_gridspec(2, 2, hspace=0.3, wspace=0.3)
    
    # Apply smoothing
    smoothing_weight = 0.6
    success_rate_smooth = smooth_curve(df['success_rate'].values, smoothing_weight)
    collision_rate_smooth = smooth_curve(df['collision_rate'].values, smoothing_weight)
    
    # ========== Plot 1: Success Rate (Top Left) ==========
    ax1 = fig.add_subplot(gs[0, 0])
    
    # Plot raw data with transparency (like TensorBoard)
    ax1.plot(df['timestep'], df['success_rate'], 
             color=TB_BLUE, alpha=0.2, linewidth=1, label='Raw')
    
    # Plot smoothed data (main curve)
    ax1.plot(df['timestep'], success_rate_smooth, 
             color=TB_BLUE, linewidth=2.5, label='Smoothed')
    
    ax1.set_xlabel('Step', fontsize=11, fontweight='normal')
    ax1.set_ylabel('Success Rate (%)', fontsize=11, fontweight='normal')
    ax1.set_title('Success Rate', fontsize=13, fontweight='600', pad=10)
    ax1.legend(loc='best', framealpha=0.9, fontsize=9)
    ax1.grid(True, alpha=0.5, linestyle='-', linewidth=0.8, color='gray')
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    
    # ========== Plot 2: Collision Rate (Top Right) ==========
    ax2 = fig.add_subplot(gs[0, 1])
    
    # Plot raw data with transparency
    ax2.plot(df['timestep'], df['collision_rate'], 
             color=TB_RED, alpha=0.2, linewidth=1, label='Raw')
    
    # Plot smoothed data
    ax2.plot(df['timestep'], collision_rate_smooth, 
             color=TB_RED, linewidth=2.5, label='Smoothed')
    
    ax2.set_xlabel('Step', fontsize=11, fontweight='normal')
    ax2.set_ylabel('Collision Rate (%)', fontsize=11, fontweight='normal')
    ax2.set_title('Collision Rate', fontsize=13, fontweight='600', pad=10)
    ax2.legend(loc='best', framealpha=0.9, fontsize=9)
    ax2.grid(True, alpha=0.5, linestyle='-', linewidth=0.8, color='gray')
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    
    # ========== Plot 3: Combined Rates (Bottom Left) ==========
    ax3 = fig.add_subplot(gs[1, 0])
    
    ax3.plot(df['timestep'], success_rate_smooth, 
             color=TB_BLUE, linewidth=2.5, label='Success Rate', marker='o', 
             markersize=3, markevery=max(1, len(df)//20))
    ax3.plot(df['timestep'], collision_rate_smooth, 
             color=TB_RED, linewidth=2.5, label='Collision Rate', marker='s', 
             markersize=3, markevery=max(1, len(df)//20))
    
    ax3.set_xlabel('Step', fontsize=11, fontweight='normal')
    ax3.set_ylabel('Rate (%)', fontsize=11, fontweight='normal')
    ax3.set_title('Success vs Collision Rate', fontsize=13, fontweight='600', pad=10)
    ax3.legend(loc='best', framealpha=0.9, fontsize=10)
    ax3.grid(True, alpha=0.5, linestyle='-', linewidth=0.8, color='gray')
    ax3.spines['top'].set_visible(False)
    ax3.spines['right'].set_visible(False)
    
    # ========== Plot 4: Episode Counts (Bottom Right) ==========
    ax4 = fig.add_subplot(gs[1, 1])
    
    # Smooth the counts too
    success_count_smooth = smooth_curve(df['success_count'].values, 0.7)
    collision_count_smooth = smooth_curve(df['collision_count'].values, 0.7)
    
    ax4.fill_between(df['timestep'], success_count_smooth, 
                     color=TB_BLUE, alpha=0.3, label='Success Count')
    ax4.plot(df['timestep'], success_count_smooth, 
             color=TB_BLUE, linewidth=2)
    
    ax4.fill_between(df['timestep'], collision_count_smooth, 
                     color=TB_RED, alpha=0.3, label='Collision Count')
    ax4.plot(df['timestep'], collision_count_smooth, 
             color=TB_RED, linewidth=2)
    
    ax4.set_xlabel('Step', fontsize=11, fontweight='normal')
    ax4.set_ylabel('Count (per batch)', fontsize=11, fontweight='normal')
    ax4.set_title('Episode Termination Counts', fontsize=13, fontweight='600', pad=10)
    ax4.legend(loc='best', framealpha=0.9, fontsize=10)
    ax4.grid(True, alpha=0.5, linestyle='-', linewidth=0.8, color='gray')
    ax4.spines['top'].set_visible(False)
    ax4.spines['right'].set_visible(False)
    
    # Add overall title
    fig.suptitle('Training Metrics - Success and Collision Analysis', 
                 fontsize=16, fontweight='bold', y=0.98)
    
    # Save plot if requested
    if save_plot:
        output_path = Path(csv_path).parent / f"{Path(csv_path).stem}_plot.png"
        plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
        print(f"\n✅ Plot saved to: {output_path}")
    
    # Show plot
    plt.show()



def main():
    parser = argparse.ArgumentParser(description='Plot success and collision metrics from CSV file')
    parser.add_argument('csv_file', nargs='?', type=str, default=None,
                       help='Path to the CSV file (optional - will auto-find latest if not provided)')
    parser.add_argument('--no-save', action='store_true', help='Do not save the plot')
    
    args = parser.parse_args()
    
    # If no CSV file provided, try to find the latest one
    if args.csv_file is None:
        print("🔍 No CSV file specified, searching for latest metrics file...")
        
        # Search in the logs directory
        logs_base = Path(r"E:\fyp\isaaclab\logs\skrl\quadcopter_winding_corridor_direct")
        
        if not logs_base.exists():
            print(f"❌ Error: Logs directory not found: {logs_base}")
            print("Please run training first or specify the CSV file path manually:")
            print("  python plot_metrics.py <path_to_csv>")
            return
        
        # Find all CSV files in metrics subdirectories
        csv_files = list(logs_base.glob("*/metrics/success_collision_metrics_*.csv"))
        
        if not csv_files:
            print(f"❌ Error: No CSV files found in {logs_base}")
            print("Please run training first to generate metrics.")
            return
        
        # Get the most recent file by modification time
        csv_path = max(csv_files, key=lambda p: p.stat().st_mtime)
        print(f"✅ Found latest CSV file: {csv_path}")
    else:
        csv_path = Path(args.csv_file)
    
    if not csv_path.exists():
        print(f"❌ Error: CSV file not found: {csv_path}")
        return
    
    plot_metrics(str(csv_path), save_plot=not args.no_save)


if __name__ == "__main__":
    main()
